// Generated by CoffeeScript 1.7.1
(function() {
  var midi, parser, start, test1, test2;

  midi = require('midi');

  parser = require('./parser');

  start = function(midi_in, port, virtual) {
    if (virtual == null) {
      virtual = false;
    }
    console.log("Opening port " + port + " - " + (midi_in.getPortName(port)));
    midi_in["open" + (virtual && 'Virtual' || '') + "Port"](port);
    return midi_in.on('message', function(deltaTime, msg) {
      return console.log("message received " + (parser.parse(port, msg)));
    });
  };

  test1 = function() {
    var midi_in1;
    midi_in1 = new midi.input();
    start(midi_in1, 0);
    return console.log('Listening to port');
  };

  test2 = function() {
    var midi_in1, midi_in2;
    midi_in1 = new midi.input();
    midi_in2 = new midi.input();
    start(midi_in1, 0);
    return console.log('Listening to port');
  };

  test1();

}).call(this);

//# sourceMappingURL=midi-test.map
