// Generated by CoffeeScript 1.7.1
(function() {
  var __slice = [].slice;

  this.parse = function(port, msg) {
    var channel;
    channel = msg[0] % 16 + 1;
    switch (msg[0] / 16) {
      case 0xB:
        return ["/" + channel + "/cc/" + msg[1], msg[2] / 127.0];
      case 0x9:
        return ["/" + channel + "/note/" + msg[1], msg[2] / 127.0];
      case 0x8:
        return ["/" + channel + "/note/" + msg[1], 0];
      case 0xE:
        return ["/" + channel + "/pitchbend/", msg[1] / 127.0];
      default:
        return ___.apply(null, [void 0, 'message:'].concat(__slice.call(msg)));
    }
  };

}).call(this);

//# sourceMappingURL=parser.map
